# Generated by Django 4.1.4 on 2023-01-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'lesson')},
        ),
    ]
